// scripts/inline-styles.mjs
//当本项目导出为依赖时，需要处理全局styles.css在第三方应应用中无法加载的问题，解决方案是将styles.css转换为内联style添加到DOM树中，在此
//第一步需要转换成ts文件中的字符串文本，方便后续处理
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const cssPath = join(__dirname, '..', 'dist', 'luxio-common','browser', 'styles.css');
const outputPath = join(__dirname, '..', 'src', 'inlined-styles.ts');

try {
  // 读取 CSS 文件
  const cssContent = await readFile(cssPath, 'utf8');

  // 转义反引号和换行（确保能安全放入模板字符串）
  const escapedCss = cssContent
    .replace(/\\/g, '\\\\')     // 转义反斜杠
    .replace(/`/g, '\\`')       // 转义反引号
    .replace(/\$/g, '\\$');     // 转义 $（避免模板字符串插值）

  // 生成 TS 文件内容
  const tsContent = `// Auto-generated by inline-styles.mjs\nexport const GLOBAL_STYLES = \`${escapedCss}\`;\n`;

  // 写入文件
  await writeFile(outputPath, tsContent, 'utf8');

  console.log('✅ Successfully inlined styles.css into inlined-styles.ts');
} catch (err) {
  console.error('❌ Failed to inline styles:', err);
  process.exit(1);
}