import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const pkgPath = join(__dirname, '..', 'package.json');
const outputPath = join(__dirname, '..', 'src', 'app-version.ts');

try {
  const pkg = JSON.parse(await readFile(pkgPath, 'utf8'));
  const version = pkg.version || '0.0.0';

  const tsContent = `// Auto-generated by version.mjs\nexport const APP_VERSION = '${version}';\n`;

  await writeFile(outputPath, tsContent, 'utf8');

  console.log(`✅ APP_VERSION set to ${version}`);
} catch (err) {
  console.error('❌ Failed to generate app version:', err);
  process.exit(1);
}
