# SPA 应用路由（支持前端 History 模式）
location / {
    root   html/official-site;
	index index.html;
    try_files $uri $uri/ /index.html;
}
location /julyware {
    root   html;
    try_files $uri $uri/ /julyware/index.html;
}

location /assistant {
    root   html;
    try_files $uri $uri/ /assistant/index.csr.html;
}

location /community-widget {
    root   html;
    try_files $uri $uri/ /community-widget/index.html;
}

location /home {
    root   html;
    try_files $uri $uri/ /home/index.html;
}

location /official-site {
    root   html;
    try_files $uri $uri/ /official-site/index.html;
}

location /signin {
    root   html;
    try_files $uri $uri/ /signin/index.html;
}

location /forgotpassword {
    root   html;
    try_files $uri $uri/ /forgotpassword/index.html;
}

location /resetpassword {
    root   html;
    try_files $uri $uri/ /resetpassword/index.html;
}

location /signup {
    root   html;
    try_files $uri $uri/ /signup/index.html;
}

location /editor {
    root   html;
    try_files $uri $uri/ /editor/index.html;
}
location /luxio-ai {
    root   html;
    try_files $uri $uri/ /luxio-ai/index.html;
}

# 共享静态资源
location /static {
	root   html;
	expires 1y;
	add_header Cache-Control "public, immutable";
}

# 后端 API 代理
location /api/auth {
    proxy_pass https://localhost:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /user {
    proxy_pass https://localhost:8980;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

# 错误页面（可选，也可放这里）
error_page 500 502 503 504 /50x.html;
location = /50x.html {
    root html;
}