import {
  Sparkles,
  CirclePlus,
  CircleHelp,
  Send,
  FileText,
  Image,
  Link2,
  AlignLeft,
  ChevronDown,
} from "lucide-react";
import { useState, useRef, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import "../styles/markdown.css";

export const projectId = "otfghdaafotnopjhqcbc";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90ZmdoZGFhZm90bm9wamhxY2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMjU3ODQsImV4cCI6MjA5MjkwMTc4NH0.c8j6HRGI3lRkTJWhWj_iKSTHlS5K2g9cOPdKmFh8ScE";
const API_BASE = `https://${projectId}.supabase.co/functions/v1/make-server-fc16f108`;
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Define the Message type
interface Message {
  id: string;
  content: string;
  role: "user" | "assistant";
  timestamp: Date;
}

// Model options for the selector
const modelOptions = [
  { value: "gpt-4o", label: "GPT-4o" },
  { value: "gpt-4o-mini", label: "GPT-4o Mini" },
  { value: "claude-sonnet-4", label: "Claude Sonnet 4" },
  { value: "deepseek-v3", label: "DeepSeek V3" },
  { value: "gemini-2.0-flash", label: "Gemini 2.0 Flash" },
];

function App() {
  // State for AI chat functionality
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputValue, setInputValue] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [selectedModel, setSelectedModel] = useState(modelOptions[0].value);
  const [modelSelectorOpen, setModelSelectorOpen] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const modelButtonRef = useRef<HTMLButtonElement>(null);
  const [dropdownUpward, setDropdownUpward] = useState(false);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Check available space and set dropdown direction when it opens
  useEffect(() => {
    if (modelSelectorOpen && modelButtonRef.current) {
      const rect = modelButtonRef.current.getBoundingClientRect();
      const spaceBelow = window.innerHeight - rect.bottom;
      const dropdownEstimatedHeight = 200;
      setDropdownUpward(spaceBelow < dropdownEstimatedHeight);
    }
  }, [modelSelectorOpen]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({
      behavior: "smooth",
    });
  };

  // Function to handle sending messages to AI
  const handleSendMessage = async () => {
    if (!inputValue.trim() || isLoading) return;

    // Add user message to chat
    const userMessage: Message = {
      id: Date.now().toString(),
      content: inputValue,
      role: "user",
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInputValue("");
    setIsLoading(true);

    try {
      // Use Supabase production environment directly
      const apiUrl = `${API_BASE}/ai_proxy`;

      const response = await fetch(apiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${publicAnonKey}`,
        },
        body: JSON.stringify({
          message: inputValue,
          model: selectedModel,
          history: messages.map((msg) => ({
            role: msg.role,
            content: msg.content,
          })),
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(
          errorData.error ||
          `API request failed with status ${response.status}`,
        );
      }

      // Create assistant message with empty content to start with
      const aiMessageId = Date.now().toString();
      const initialAiMessage: Message = {
        id: aiMessageId,
        content: "",
        role: "assistant",
        timestamp: new Date(),
      };

      // Add the initial empty message to the messages array
      setMessages((prev) => [...prev, initialAiMessage]);

      // Process the streamed response
      const reader = response.body?.getReader();
      if (!reader) {
        throw new Error("Could not read response stream");
      }

      let aiContent = "";
      const decoder = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        // Decode the chunk and append to the AI content
        const chunk = decoder.decode(value, { stream: true });
        aiContent += chunk;

        // Update the assistant message with the new content
        setMessages((prev) =>
          prev.map((msg) =>
            msg.id === aiMessageId
              ? { ...msg, content: aiContent }
              : msg,
          ),
        );
      }

      // Update the final message content after stream completes
      setMessages((prev) =>
        prev.map((msg) =>
          msg.id === aiMessageId
            ? { ...msg, content: aiContent }
            : msg,
        ),
      );
    } catch (error) {
      console.error("Error communicating with AI:", error);

      const errorMessage: Message = {
        id: Date.now().toString(),
        content:
          "抱歉，我在处理您的请求时遇到了错误。请稍后再试。",
        role: "assistant",
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  // Handle key press for Enter to send message
  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <div className="text-purple-500">
              <Sparkles className="w-8 h-8 fill-purple-500" />
            </div>
            <h1 className="text-2xl">AI 助手对话</h1>
          </div>
          {/* <img src={exampleImage} alt="Profile" className="w-10 h-10 rounded-full" /> */}
        </div>

        {/* Chat Messages Container */}
        <div className="bg-white rounded-2xl shadow-sm p-4 mb-4 h-[400px] overflow-y-auto">
          {messages.length > 0 ? (
            <div className="space-y-4">
              {messages.map((msg) => (
                <div
                  key={msg.id}
                  className={`p-3 rounded-lg max-w-[80%] ${msg.role === "user"
                      ? "bg-purple-100 ml-auto"
                      : "bg-gray-100"
                    }`}
                >
                  <div className="font-medium text-xs mb-1">
                    {msg.role === "user" ? "您" : "AI 助手"}
                  </div>
                  <div className="text-sm markdown-content">
                    {msg.role === "assistant" ? (
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {msg.content}
                      </ReactMarkdown>
                    ) : (
                      <div className="whitespace-pre-wrap">{msg.content}</div>
                    )}
                  </div>
                </div>
              ))}
              {isLoading && (
                <div className="p-3 rounded-lg bg-gray-100 max-w-[80%]">
                  <div className="font-medium text-xs mb-1">
                    AI 助手
                  </div>
                  <div className="text-sm">正在思考中...</div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-gray-500">
              <Sparkles className="w-12 h-12 text-purple-400 mb-4" />
              <p>开始与 AI 助手对话，分享您的想法或提出问题</p>
              <div className="mt-4 grid grid-cols-2 gap-3 max-w-md">
                <button
                  onClick={() =>
                    setInputValue("介绍了最新的AI技术")
                  }
                  className="text-left p-3 text-sm bg-gray-50 hover:bg-gray-100 rounded-lg"
                >
                  介绍AI技术
                </button>
                <button
                  onClick={() =>
                    setInputValue("帮我写一段关于创新的文案")
                  }
                  className="text-left p-3 text-sm bg-gray-50 hover:bg-gray-100 rounded-lg"
                >
                  创新文案
                </button>
                <button
                  onClick={() =>
                    setInputValue("如何提高工作效率")
                  }
                  className="text-left p-3 text-sm bg-gray-50 hover:bg-gray-100 rounded-lg"
                >
                  工作效率
                </button>
                <button
                  onClick={() =>
                    setInputValue("给我一些学习建议")
                  }
                  className="text-left p-3 text-sm bg-gray-50 hover:bg-gray-100 rounded-lg"
                >
                  学习建议
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Input Area */}
        <div className="bg-white rounded-2xl shadow-sm border-2 border-purple-200 p-4">
          <div className="mb-4">
            <textarea
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={handleKeyPress}
              placeholder="输入您的消息..."
              className="w-full text-lg outline-none min-h-[60px] resize-none"
            />
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              {/* Model Selector */}
              <div className="relative">
                <button
                  ref={modelButtonRef}
                  onClick={() => setModelSelectorOpen(!modelSelectorOpen)}
                  className="flex items-center gap-2 px-3 py-1.5 text-sm hover:bg-gray-50 rounded-lg transition-colors border border-gray-200"
                >
                  <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>
                  </svg>
                  <span>{modelOptions.find(m => m.value === selectedModel)?.label || selectedModel}</span>
                  <ChevronDown className="w-3.5 h-3.5 text-gray-400" />
                </button>
                {modelSelectorOpen && (
                  <div className={`absolute left-0 z-50 min-w-[160px] ${dropdownUpward ? "bottom-full mb-1" : "top-full mt-1"} bg-white border border-gray-200 rounded-lg shadow-lg`}>
                    {modelOptions.map((model) => (
                      <button
                        key={model.value}
                        onClick={() => {
                          setSelectedModel(model.value);
                          setModelSelectorOpen(false);
                        }}
                        className={`w-full text-left px-3 py-2 text-sm hover:bg-gray-50 transition-colors ${
                          selectedModel === model.value ? 'bg-purple-50 text-purple-700 font-medium' : ''
                        } ${model === modelOptions[0] ? "rounded-t-lg" : ""} ${
                          model === modelOptions[modelOptions.length - 1] ? 'rounded-b-lg' : ''
                        }`}
                      >
                        {model.label}
                      </button>
                    ))}
                  </div>
                )}
                {/* Click outside to close */}
                {modelSelectorOpen && (
                  <div
                    className="fixed inset-0 z-40"
                    onClick={() => setModelSelectorOpen(false)}
                  />
                )}
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setInputValue("")}
                className="p-2 hover:bg-gray-50 rounded-lg transition-colors"
                title="清空输入"
              >
                <CirclePlus className="w-5 h-5 text-gray-600" />
              </button>
              <button
                className="p-2 hover:bg-gray-50 rounded-lg transition-colors"
                title="帮助"
              >
                <CircleHelp className="w-5 h-5 text-gray-600" />
              </button>
              <button
                onClick={handleSendMessage}
                disabled={isLoading || !inputValue.trim()}
                className={`p-2.5 rounded-full ${isLoading || !inputValue.trim()
                    ? "bg-gray-300 cursor-not-allowed"
                    : "bg-gradient-to-r from-purple-400 to-pink-400 hover:from-purple-500 hover:to-pink-500"
                  } transition-colors`}
              >
                <Send className="w-5 h-5 text-white" />
              </button>
            </div>
          </div>
        </div>

        {/* Bottom Actions */}
        <div className="flex items-center gap-4 mt-4 px-2 text-sm text-gray-600">
          <button className="flex items-center gap-2 hover:text-gray-900 transition-colors">
            <FileText className="w-4 h-4" />
            <span>文档/PDF/音频</span>
          </button>
          <button className="flex items-center gap-2 hover:text-gray-900 transition-colors">
            <Image className="w-4 h-4" />
            <span>图片描述</span>
          </button>
          <button className="flex items-center gap-2 hover:text-gray-900 transition-colors">
            <Link2 className="w-4 h-4" />
            <span>网页分析</span>
          </button>
          <button className="flex items-center gap-2 hover:text-gray-900 transition-colors">
            <AlignLeft className="w-4 h-4" />
            <span>总结长文本</span>
          </button>
        </div>
      </div>
    </div>
  );
}

export default App;