import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';
import express from 'express';
import { existsSync } from 'node:fs';
import { createServer } from '@luxio/agent';
import type { Connect } from 'vite';

declare const isProdBuild: boolean | undefined;

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const isCompiled = typeof isProdBuild !== 'undefined' && isProdBuild === true;
const isDev = !isCompiled;
const rootDir = resolve(__dirname, '..');
const distDir = isCompiled ? join(__dirname, 'dist') : join(rootDir, 'dist');

const app = express();

let viteMiddlewares: Connect.Server | undefined;

if (isDev) {
  const { createServer: createViteServer } = await import('vite');
  const vite = await createViteServer({
    root: rootDir,
    server: { middlewareMode: true },
    appType: 'spa',
  });
  viteMiddlewares = vite.middlewares;

  // Reuse the mkcert certs generated by vite-plugin-mkcert so the
  // dev server stays HTTPS on 5178 (see common/vite-proxy.ts).
  const mkcertDir = join(homedir(), '.vite-plugin-mkcert');
  const certFile = join(mkcertDir, 'cert.pem');
  const keyFile = join(mkcertDir, 'dev.pem');
  if (existsSync(certFile) && existsSync(keyFile)) {
    process.env['SSL_CERT_PATH'] = certFile;
    process.env['SSL_KEY_PATH'] = keyFile;
  } else {
    console.warn('[Editor Server] mkcert certs not found, falling back to http');
  }
}

createServer({
  portEnvKey: 'PORT',
  defaultPort: 5178,
  tokenSecretEnvKey: 'EDITOR_TOKEN_SECRET',
  corsPorts: [5178, 5179, 5173, 4200, 4000],
  rootDir,
  logPrefix: '[Editor Server]',
  logUrlPath: '/editor',
  staticDir: isDev ? undefined : distDir,
  app,
});

// Mount vite AFTER agent routes so /api/local/* reaches the agent
// instead of vite's SPA fallback serving index.html.
if (isDev && viteMiddlewares) {
  app.use(viteMiddlewares);
}

if (!isDev) {
  // The built SPA uses base-relative asset URLs (./assets/...), which
  // resolve under /editor/ when served at that prefix. Serve static and
  // SPA fallback under /editor as well as at the root.
  app.use('/editor', express.static(distDir, { index: false, redirect: false, maxAge: '1y' }));
  app.use('/editor', (_req, res) => {
    res.sendFile(join(distDir, 'index.html'));
  });
  app.use((_req, res) => {
    res.sendFile(join(distDir, 'index.html'));
  });
}
