// Auto-generated by inline-styles.mjs
export const GLOBAL_STYLES = `/* src/styles.css */
/*! tailwindcss v4.3.1 | MIT License | https://tailwindcss.com */
@layer properties;
@layer theme, base, components, utilities;
@layer theme {
  :root,
  :host {
    --font-sans:
      ui-sans-serif,
      system-ui,
      sans-serif,
      "Apple Color Emoji",
      "Segoe UI Emoji",
      "Segoe UI Symbol",
      "Noto Color Emoji";
    --font-mono:
      ui-monospace,
      SFMono-Regular,
      Menlo,
      Monaco,
      Consolas,
      "Liberation Mono",
      "Courier New",
      monospace;
    --color-pink-200: oklch(89.9% 0.061 343.231);
    --color-gray-600: oklch(44.6% 0.03 256.802);
    --spacing: 0.25rem;
    --default-transition-duration: 150ms;
    --default-transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    --default-font-family: var(--font-sans);
    --default-mono-font-family: var(--font-mono);
  }
}
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    border: 0 solid;
  }
  html,
  :host {
    line-height: 1.5;
    -webkit-text-size-adjust: 100%;
    tab-size: 4;
    font-family: var(--default-font-family, ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji");
    font-feature-settings: var(--default-font-feature-settings, normal);
    font-variation-settings: var(--default-font-variation-settings, normal);
    -webkit-tap-highlight-color: transparent;
  }
  hr {
    height: 0;
    color: inherit;
    border-top-width: 1px;
  }
  abbr:where([title]) {
    -webkit-text-decoration: underline dotted;
    text-decoration: underline dotted;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    font-size: inherit;
    font-weight: inherit;
  }
  a {
    color: inherit;
    -webkit-text-decoration: inherit;
    text-decoration: inherit;
  }
  b,
  strong {
    font-weight: bolder;
  }
  code,
  kbd,
  samp,
  pre {
    font-family: var(--default-mono-font-family, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace);
    font-feature-settings: var(--default-mono-font-feature-settings, normal);
    font-variation-settings: var(--default-mono-font-variation-settings, normal);
    font-size: 1em;
  }
  small {
    font-size: 80%;
  }
  sub,
  sup {
    font-size: 75%;
    line-height: 0;
    position: relative;
    vertical-align: baseline;
  }
  sub {
    bottom: -0.25em;
  }
  sup {
    top: -0.5em;
  }
  table {
    text-indent: 0;
    border-color: inherit;
    border-collapse: collapse;
  }
  :-moz-focusring {
    outline: auto;
  }
  progress {
    vertical-align: baseline;
  }
  summary {
    display: list-item;
  }
  ol,
  ul,
  menu {
    list-style: none;
  }
  img,
  svg,
  video,
  canvas,
  audio,
  iframe,
  embed,
  object {
    display: block;
    vertical-align: middle;
  }
  img,
  video {
    max-width: 100%;
    height: auto;
  }
  button,
  input,
  select,
  optgroup,
  textarea,
  ::file-selector-button {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    border-radius: 0;
    background-color: transparent;
    opacity: 1;
  }
  :where(select:is([multiple], [size])) optgroup {
    font-weight: bolder;
  }
  :where(select:is([multiple], [size])) optgroup option {
    padding-inline-start: 20px;
  }
  ::file-selector-button {
    margin-inline-end: 4px;
  }
  ::placeholder {
    opacity: 1;
  }
  @supports (not (-webkit-appearance: -apple-pay-button)) or (contain-intrinsic-size: 1px) {
    ::placeholder {
      color: currentcolor;
      @supports (color: color-mix(in lab, red, red)) {
        color: color-mix(in oklab, currentcolor 50%, transparent);
      }
    }
  }
  textarea {
    resize: vertical;
  }
  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }
  ::-webkit-date-and-time-value {
    min-height: 1lh;
    text-align: inherit;
  }
  ::-webkit-datetime-edit {
    display: inline-flex;
  }
  ::-webkit-datetime-edit-fields-wrapper {
    padding: 0;
  }
  ::-webkit-datetime-edit,
  ::-webkit-datetime-edit-year-field,
  ::-webkit-datetime-edit-month-field,
  ::-webkit-datetime-edit-day-field,
  ::-webkit-datetime-edit-hour-field,
  ::-webkit-datetime-edit-minute-field,
  ::-webkit-datetime-edit-second-field,
  ::-webkit-datetime-edit-millisecond-field,
  ::-webkit-datetime-edit-meridiem-field {
    padding-block: 0;
  }
  ::-webkit-calendar-picker-indicator {
    line-height: 1;
  }
  :-moz-ui-invalid {
    box-shadow: none;
  }
  button,
  input:where([type=button], [type=reset], [type=submit]),
  ::file-selector-button {
    appearance: button;
  }
  ::-webkit-inner-spin-button,
  ::-webkit-outer-spin-button {
    height: auto;
  }
  [hidden]:where(:not([hidden=until-found])) {
    display: none !important;
  }
}
@layer utilities {
  .visible {
    visibility: visible;
  }
  .fixed {
    position: fixed;
  }
  .static {
    position: static;
  }
  .container {
    width: 100%;
    @media (width >= 40rem) {
      max-width: 40rem;
    }
    @media (width >= 48rem) {
      max-width: 48rem;
    }
    @media (width >= 64rem) {
      max-width: 64rem;
    }
    @media (width >= 80rem) {
      max-width: 80rem;
    }
    @media (width >= 96rem) {
      max-width: 96rem;
    }
  }
  .m-48 {
    margin: calc(var(--spacing) * 48);
  }
  .block {
    display: block;
  }
  .flex {
    display: flex;
  }
  .hidden {
    display: none;
  }
  .inline {
    display: inline;
  }
  .inline-flex {
    display: inline-flex;
  }
  .table {
    display: table;
  }
  .h-3 {
    height: calc(var(--spacing) * 3);
  }
  .h-7 {
    height: calc(var(--spacing) * 7);
  }
  .h-full {
    height: 100%;
  }
  .w-3 {
    width: calc(var(--spacing) * 3);
  }
  .w-7 {
    width: calc(var(--spacing) * 7);
  }
  .w-full {
    width: 100%;
  }
  .flex-grow {
    flex-grow: 1;
  }
  .border-collapse {
    border-collapse: collapse;
  }
  .transform {
    transform: var(--tw-rotate-x,) var(--tw-rotate-y,) var(--tw-rotate-z,) var(--tw-skew-x,) var(--tw-skew-y,);
  }
  .cursor-pointer {
    cursor: pointer;
  }
  .resize {
    resize: both;
  }
  .flex-wrap {
    flex-wrap: wrap;
  }
  .items-center {
    align-items: center;
  }
  .gap-1 {
    gap: var(--spacing);
  }
  .overflow-hidden {
    overflow: hidden;
  }
  .rounded {
    border-radius: 0.25rem;
  }
  .rounded-full {
    border-radius: calc(infinity * 1px);
  }
  .border {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }
  .bg-pink-200 {
    background-color: var(--color-pink-200);
  }
  .mask-repeat {
    mask-repeat: repeat;
  }
  .object-cover {
    object-fit: cover;
  }
  .text-gray-600 {
    color: var(--color-gray-600);
  }
  .italic {
    font-style: italic;
  }
  .line-through {
    text-decoration-line: line-through;
  }
  .overline {
    text-decoration-line: overline;
  }
  .underline {
    text-decoration-line: underline;
  }
  .shadow {
    --tw-shadow: 0 1px 3px 0 var(--tw-shadow-color, rgb(0 0 0 / 0.1)), 0 1px 2px -1px var(--tw-shadow-color, rgb(0 0 0 / 0.1));
    box-shadow:
      var(--tw-inset-shadow),
      var(--tw-inset-ring-shadow),
      var(--tw-ring-offset-shadow),
      var(--tw-ring-shadow),
      var(--tw-shadow);
  }
  .outline {
    outline-style: var(--tw-outline-style);
    outline-width: 1px;
  }
  .blur {
    --tw-blur: blur(8px);
    filter: var(--tw-blur,) var(--tw-brightness,) var(--tw-contrast,) var(--tw-grayscale,) var(--tw-hue-rotate,) var(--tw-invert,) var(--tw-saturate,) var(--tw-sepia,) var(--tw-drop-shadow,);
  }
  .filter {
    filter: var(--tw-blur,) var(--tw-brightness,) var(--tw-contrast,) var(--tw-grayscale,) var(--tw-hue-rotate,) var(--tw-invert,) var(--tw-saturate,) var(--tw-sepia,) var(--tw-drop-shadow,);
  }
  .transition {
    transition-property:
      color,
      background-color,
      border-color,
      outline-color,
      text-decoration-color,
      fill,
      stroke,
      --tw-gradient-from,
      --tw-gradient-via,
      --tw-gradient-to,
      opacity,
      box-shadow,
      transform,
      translate,
      scale,
      rotate,
      filter,
      -webkit-backdrop-filter,
      backdrop-filter,
      display,
      content-visibility,
      overlay,
      pointer-events;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }
  .hover\\:opacity-80 {
    &:hover {
      @media (hover: hover) {
        opacity: 80%;
      }
    }
  }
}
.xterm {
  cursor: text;
  position: relative;
  user-select: none;
  -ms-user-select: none;
  -webkit-user-select: none;
}
.xterm.focus,
.xterm:focus {
  outline: none;
}
.xterm .xterm-helpers {
  position: absolute;
  top: 0;
  z-index: 5;
}
.xterm .xterm-helper-textarea {
  padding: 0;
  border: 0;
  margin: 0;
  position: absolute;
  opacity: 0;
  left: -9999em;
  top: 0;
  width: 0;
  height: 0;
  z-index: -5;
  white-space: nowrap;
  overflow: hidden;
  resize: none;
}
.xterm .composition-view {
  background: #000;
  color: #FFF;
  display: none;
  position: absolute;
  white-space: nowrap;
  z-index: 1;
}
.xterm .composition-view.active {
  display: block;
}
.xterm .xterm-viewport {
  overflow-y: scroll;
  cursor: default;
  position: absolute;
  right: 0;
  left: 0;
  top: 0;
  bottom: 0;
}
.xterm:not(.allow-transparency) .xterm-viewport {
  background-color: #000;
}
.xterm .xterm-screen {
  position: relative;
}
.xterm .xterm-screen canvas {
  position: absolute;
  left: 0;
  top: 0;
}
.xterm.enable-mouse-events {
  cursor: default;
}
.xterm.xterm-cursor-pointer,
.xterm .xterm-cursor-pointer {
  cursor: pointer;
}
.xterm.column-select.focus {
  cursor: crosshair;
}
.xterm .xterm-accessibility:not(.debug),
.xterm .xterm-message {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  z-index: 10;
  color: transparent;
  pointer-events: none;
}
.xterm .xterm-accessibility-tree:not(.debug) *::selection {
  color: transparent;
}
.xterm .xterm-accessibility-tree {
  font-family: monospace;
  -webkit-user-select: text;
  user-select: text;
  white-space: pre;
}
.xterm .xterm-accessibility-tree > div {
  transform-origin: left;
  width: fit-content;
}
.xterm .live-region {
  position: absolute;
  left: -9999px;
  width: 1px;
  height: 1px;
  overflow: hidden;
}
.xterm-dim {
  opacity: 1 !important;
}
.xterm-underline-1 {
  text-decoration: underline;
}
.xterm-underline-2 {
  text-decoration: double underline;
}
.xterm-underline-3 {
  text-decoration: wavy underline;
}
.xterm-underline-4 {
  text-decoration: dotted underline;
}
.xterm-underline-5 {
  text-decoration: dashed underline;
}
.xterm-overline {
  text-decoration: overline;
}
.xterm-overline.xterm-underline-1 {
  text-decoration: overline underline;
}
.xterm-overline.xterm-underline-2 {
  text-decoration: overline double underline;
}
.xterm-overline.xterm-underline-3 {
  text-decoration: overline wavy underline;
}
.xterm-overline.xterm-underline-4 {
  text-decoration: overline dotted underline;
}
.xterm-overline.xterm-underline-5 {
  text-decoration: overline dashed underline;
}
.xterm-strikethrough {
  text-decoration: line-through;
}
.xterm-screen .xterm-decoration-container .xterm-decoration {
  z-index: 6;
  position: absolute;
}
.xterm-screen .xterm-decoration-container .xterm-decoration.xterm-decoration-top-layer {
  z-index: 7;
}
.xterm-decoration-overview-ruler {
  z-index: 8;
  position: absolute;
  top: 0;
  right: 0;
  pointer-events: none;
}
.xterm-decoration-top {
  z-index: 2;
  position: relative;
}
.xterm .xterm-scrollable-element > .xterm-scrollbar {
  cursor: default;
}
.xterm .xterm-scrollable-element > .xterm-scrollbar > .xterm-scra {
  cursor: pointer;
  background-color: var(--vscode-scrollbarSliderBackground, rgba(100, 100, 100, 0.4));
  mask-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 11 11'><path d='M2.5 8.5 L5.5 2.5 L8.5 8.5 Z' fill='black'/></svg>");
  -webkit-mask-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 11 11'><path d='M2.5 8.5 L5.5 2.5 L8.5 8.5 Z' fill='black'/></svg>");
  mask-repeat: no-repeat;
  -webkit-mask-repeat: no-repeat;
  mask-position: center center;
  -webkit-mask-position: center center;
  mask-size: 100% 100%;
  -webkit-mask-size: 100% 100%;
}
.xterm .xterm-scrollable-element > .xterm-scrollbar > .xterm-scra.xterm-arrow-down {
  transform: rotate(180deg);
}
.xterm .xterm-scrollable-element > .xterm-visible {
  opacity: 1;
  background: rgba(0, 0, 0, 0);
  transition: opacity 100ms linear;
  z-index: 11;
}
.xterm .xterm-scrollable-element > .xterm-invisible {
  opacity: 0;
  pointer-events: none;
}
.xterm .xterm-scrollable-element > .xterm-invisible.xterm-fade {
  transition: opacity 800ms linear;
}
.xterm .xterm-scrollable-element > .xterm-shadow {
  position: absolute;
  display: none;
}
.xterm .xterm-scrollable-element > .xterm-shadow.xterm-shadow-top {
  display: block;
  top: 0;
  left: 3px;
  height: 3px;
  width: 100%;
  box-shadow: var(--vscode-scrollbar-shadow, #000) 0 6px 6px -6px inset;
}
.xterm .xterm-scrollable-element > .xterm-shadow.xterm-shadow-left {
  display: block;
  top: 3px;
  left: 0;
  height: 100%;
  width: 3px;
  box-shadow: var(--vscode-scrollbar-shadow, #000) 6px 0 6px -6px inset;
}
.xterm .xterm-scrollable-element > .xterm-shadow.xterm-shadow-top-left-corner {
  display: block;
  top: 0;
  left: 0;
  height: 3px;
  width: 3px;
}
.xterm .xterm-scrollable-element > .xterm-shadow.xterm-shadow-top.xterm-shadow-left {
  box-shadow: var(--vscode-scrollbar-shadow, #000) 6px 0 6px -6px inset;
}
:root {
  --a2ui-button-background:
    linear-gradient(
      
      135deg,
      light-dark(var(--p-70), var(--p-40)) 0%,
      light-dark(var(--p-60), var(--p-30)) 100% );
  --a2ui-button-box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
  --a2ui-button-font-weight: 500;
  --a2ui-button-border-radius: 9999px;
  --a2ui-text-a-color: var(--e-40, red);
  --a2ui-text-a-font-weight: bold;
  --a2ui-card-border: none;
  --a2ui-card-border-radius: 24px;
  --a2ui-card-background:
    radial-gradient(
      
      circle at top left,
      light-dark(transparent, rgba(6, 182, 212, 0.15)),
      transparent 40% ),
    radial-gradient(
      
      circle at bottom right,
      light-dark(transparent, rgba(139, 92, 246, 0.15)),
      transparent 40% ),
    linear-gradient(
      
      135deg,
      light-dark(rgba(255, 255, 255, 0.7), rgba(30, 41, 59, 0.7)),
      light-dark(rgba(255, 255, 255, 0.7), rgba(15, 23, 42, 0.8)) );
  --a2ui-image-border-radius: 12px;
  --a2ui-checkbox-label-font-size: 0.875rem;
  --a2ui-checkbox-background: light-dark(var(--n-100), var(--n-20));
  --a2ui-checkbox-border: 1px solid light-dark(var(--p-60), var(--p-40));
  --a2ui-choicepicker-gap: 0.5rem;
  --a2ui-choicepicker-padding: 0.5rem;
  --a2ui-choicepicker-label-color: light-dark(var(--n-20), var(--n-90));
  --a2ui-choicepicker-label-font-size: 0.875rem;
  --a2ui-datetimeinput-background: light-dark(var(--n-100), var(--n-20));
  --a2ui-datetimeinput-border: 1px solid light-dark(var(--n-80), var(--n-30));
  --a2ui-datetimeinput-padding: 0.5rem;
  --a2ui-list-padding: 0.5rem;
  --a2ui-slider-track-margin: 0.25rem 0;
  --a2ui-slider-thumb-margin: -0.25rem 0;
}
:root {
  --vscode-font-family:
    "Segoe UI",
    Tahoma,
    Geneva,
    Verdana,
    sans-serif;
  --vscode-font-size: 14px;
  --vscode-font-weight: 400;
  --vscode-line-height: 1.5;
  --vscode-font-mono: "Courier New", monospace;
  --vscode-code-font-size: 13px;
  --vscode-terminal-font-family: var(--vscode-font-mono);
  --vscode-terminal-font-size: var(--vscode-code-font-size);
  --vscode-heading-font-family: var(--vscode-font-family);
  --vscode-heading-font-weight: 600;
  --vscode-label-font-size: 13px;
  --vscode-label-font-weight: 400;
  --vscode-input-font-size: 14px;
  --vscode-button-font-size: 14px;
  --vscode-button-font-weight: 500;
  --vscode-menu-font-size: 13px;
  --vscode-tab-font-size: 13px;
  --vscode-tree-font-size: 13px;
  --vscode-badge-font-size: 11px;
  --vscode-small-font-size: 12px;
  --vscode-radius-sm: 4px;
  --vscode-radius-md: 10px;
  --vscode-radius-lg: 16px;
  --vscode-radius-pill: 9999px;
  --vscode-shadow-sm: 0 2px 8px rgba(0, 0, 0, 0.1);
  --vscode-shadow-md: 0 8px 24px rgba(0, 0, 0, 0.15);
  --vscode-shadow-lg: 0 18px 50px rgba(0, 0, 0, 0.22);
  --vscode-background: #ffffff;
  --vscode-foreground: #616161;
  --vscode-editor-background: #ffffff;
  --vscode-sideBar-background: #f8f8f8;
  --vscode-tab-inactiveBackground: #eef0f2;
  --vscode-tab-activeBackground: #ffffff;
  --vscode-tab-border: #f0f0f0;
  --vscode-panel-background: #f3f3f3;
  --vscode-statusBar-background: #007acc;
  --vscode-statusBar-foreground: #ffffff;
  --vscode-button-background: rgb(213, 203, 203);
  --vscode-button-foreground: #ffffff;
  --vscode-input-background: #ffffff;
  --vscode-input-border: #ddd;
  --vscode-list-hoverBackground: #e8e8e8;
  --vscode-list-activeSelectionBackground: #0060c0;
  --vscode-list-activeSelectionForeground: #ffffff;
  --vscode-list-inactiveSelectionBackground: #e4e6f1;
  --vscode-editorGroup-border: #e7e7e7;
  --vscode-editorWidget-background: #f3f3f3;
  --vscode-titleBar-activeBackground: #dddddd;
  --vscode-titleBar-inactiveBackground: #dddddd;
  --vscode-activityBar-background: #f8f8f8;
  --vscode-activityBar-foreground: #616161;
  --vscode-activityBar-inactiveForeground: #616161;
  --vscode-activityBarBadge-background: #007acc;
  --vscode-activityBarBadge-foreground: #ffffff;
  --vscode-icon-foreground: #616161;
  --vscode-focusBorder: #0078d4;
  --vscode-textLink-foreground: #006ab1;
  --vscode-textLink-activeForeground: #006ab1;
  --vscode-textSeparator-foreground: #0000002e;
  --vscode-scrollbar-background: #ccc;
  --vscode-tabborder-background: rgb(204, 204, 204);
  --vscode-cursor-foreground: #616161;
  --vscode-text-selectionBackground: #cce0ff;
  --n-100: #ffffff;
  --n-95: #f1f1f1;
  --n-90: #e2e2e2;
  --n-80: #c6c6c6;
  --n-70: #ababab;
  --n-40: #5e5e5e;
  --n-30: #474747;
  --n-20: #303030;
  --n-10: #1b1b1b;
  --n-0: #000000;
  --p-70: #a0a3ff;
  --p-60: #8487ea;
  --p-40: #5154b3;
  --p-30: #383b99;
  --e-95: #ffedea;
  --e-80: #ffb4ab;
  --e-40: #ba1a1a;
  --bb-grid-size: 4px;
  --bb-grid-size-2: calc(var(--bb-grid-size) * 2);
  --bb-grid-size-3: calc(var(--bb-grid-size) * 3);
  --bb-grid-size-4: calc(var(--bb-grid-size) * 4);
  --bb-grid-size-5: calc(var(--bb-grid-size) * 5);
  --bb-grid-size-6: calc(var(--bb-grid-size) * 6);
  --bb-grid-size-7: calc(var(--bb-grid-size) * 7);
  --bb-grid-size-8: calc(var(--bb-grid-size) * 8);
  --bb-grid-size-9: calc(var(--bb-grid-size) * 9);
  --bb-grid-size-10: calc(var(--bb-grid-size) * 10);
  --bb-grid-size-11: calc(var(--bb-grid-size) * 11);
  --bb-grid-size-12: calc(var(--bb-grid-size) * 12);
  --bb-grid-size-13: calc(var(--bb-grid-size) * 13);
  --bb-grid-size-14: calc(var(--bb-grid-size) * 14);
  --bb-grid-size-15: calc(var(--bb-grid-size) * 15);
  --bb-grid-size-16: calc(var(--bb-grid-size) * 16);
  --background:
    radial-gradient(
      
      at 0% 0%,
      light-dark(rgba(161, 196, 253, 0.3), rgba(6, 182, 212, 0.15)) 0px,
      transparent 50% ),
    radial-gradient(
      
      at 100% 0%,
      light-dark(rgba(255, 226, 226, 0.3), rgba(59, 130, 246, 0.15)) 0px,
      transparent 50% ),
    radial-gradient(
      
      at 100% 100%,
      light-dark(rgba(162, 210, 255, 0.3), rgba(20, 184, 166, 0.15)) 0px,
      transparent 50% ),
    radial-gradient(
      
      at 0% 100%,
      light-dark(rgba(255, 200, 221, 0.3), rgba(99, 102, 241, 0.15)) 0px,
      transparent 50% ),
    linear-gradient(
      120deg,
      light-dark(#f0f4f8, #0f172a) 0%,
      light-dark(#e2e8f0, #1e293b) 100%);
}
[data-theme=dark] {
  --vscode-font-family:
    "Segoe UI",
    Tahoma,
    Geneva,
    Verdana,
    sans-serif;
  --vscode-font-size: 14px;
  --vscode-font-weight: 400;
  --vscode-line-height: 1.5;
  --vscode-font-mono: "Courier New", monospace;
  --vscode-code-font-size: 13px;
  --vscode-terminal-font-family: var(--vscode-font-mono);
  --vscode-terminal-font-size: var(--vscode-code-font-size);
  --vscode-heading-font-family: var(--vscode-font-family);
  --vscode-heading-font-weight: 600;
  --vscode-label-font-size: 13px;
  --vscode-label-font-weight: 400;
  --vscode-input-font-size: 14px;
  --vscode-button-font-size: 14px;
  --vscode-button-font-weight: 500;
  --vscode-menu-font-size: 13px;
  --vscode-tab-font-size: 13px;
  --vscode-tree-font-size: 13px;
  --vscode-badge-font-size: 11px;
  --vscode-small-font-size: 12px;
  --vscode-radius-sm: 4px;
  --vscode-radius-md: 10px;
  --vscode-radius-lg: 16px;
  --vscode-radius-pill: 9999px;
  --vscode-shadow-sm: 0 2px 8px rgba(0, 0, 0, 0.1);
  --vscode-shadow-md: 0 8px 24px rgba(0, 0, 0, 0.15);
  --vscode-shadow-lg: 0 18px 50px rgba(0, 0, 0, 0.22);
  --vscode-background: #1f1f1f;
  --vscode-foreground: #cccccc;
  --vscode-editor-background: #1e1e1e;
  --vscode-sideBar-background: #181818;
  --vscode-tab-inactiveBackground: #252526;
  --vscode-tab-activeBackground: #1e1e1e;
  --vscode-tab-border: #252526;
  --vscode-panel-background: #181818;
  --vscode-statusBar-background: #0078d4;
  --vscode-statusBar-foreground: #ffffff;
  --vscode-button-background: #0078d4;
  --vscode-button-foreground: #ffffff;
  --vscode-input-background: #3c3c3c;
  --vscode-input-border: #3c3c3c;
  --vscode-list-hoverBackground: #2a2d2e;
  --vscode-list-activeSelectionBackground: #2f3337;
  --vscode-list-activeSelectionForeground: #d7dae0;
  --vscode-list-inactiveSelectionBackground: #3a3d41;
  --vscode-editorGroup-border: #454545;
  --vscode-editorWidget-background: #252526;
  --vscode-titleBar-activeBackground: #3c3c3c;
  --vscode-titleBar-inactiveBackground: #3c3c3c;
  --vscode-activityBar-background: #333333;
  --vscode-activityBar-foreground: #ffffff;
  --vscode-activityBar-inactiveForeground: #ffffff66;
  --vscode-activityBarBadge-background: #0078d4;
  --vscode-activityBarBadge-foreground: #ffffff;
  --vscode-icon-foreground: #cccccc;
  --vscode-focusBorder: #0078d4;
  --vscode-textLink-foreground: #4daafc;
  --vscode-textLink-activeForeground: #4daafc;
  --vscode-textSeparator-foreground: #ffffff2e;
  --vscode-scrollbar-background: #1f1f1f;
  --vscode-tabborder-background: rgba(0, 0, 0, 0);
  --vscode-cursor-foreground: #ffffff;
  --vscode-text-selectionBackground: #264f78;
}
html {
  height: 100%;
}
*,
*::before,
*::after {
  box-sizing: border-box;
}
body,
body::before,
body::after {
  height: 100%;
  margin: 0;
  font-family: var(--vscode-font-family, "Segoe UI", Tahoma, Geneva, Verdana, sans-serif);
  font-size: var(--vscode-font-size, 14px);
  font-weight: var(--vscode-font-weight, 400);
  line-height: var(--vscode-line-height, 1.5);
  background-color: var(--vscode-background);
  color: var(--vscode-foreground);
}
img,
svg {
  vertical-align: middle;
}
.btn-svg:hover {
  background-color: var(--vscode-list-hoverBackground);
  color: var(--vscode-activityBar-foreground);
  cursor: pointer;
}
.btn-text {
  cursor: pointer;
}
.cm-editor .cm-content {
  cursor: text;
}
.codigma-menu-every-item {
  align-items: center;
  color: var(--vscode-foreground);
  display: flex;
  font-size: 16px;
  font-weight: 400;
  height: 36px;
  justify-content: start;
  word-wrap: break-word;
  cursor: pointer;
  padding: 12px 16px;
  border-bottom: 1px solid var(--vscode-editorGroup-border);
  transition: background-color 0.2s;
  background-color: var(--vscode-sideBar-background);
}
.codigma-menu-every-item:hover {
  background-color: var(--vscode-list-hoverBackground);
}
.codigma-menu-every-item:last-child {
  border-bottom: none;
}
.codigma-menu-every-item svg,
.codigma-menu-every-item img {
  margin-right: 16px;
  color: var(--vscode-icon-foreground);
}
.custom-scroll {
  scrollbar-width: thin;
  scrollbar-color: var(--vscode-scrollbar-background) transparent;
  overflow-y: scroll;
}
.custom-scroll::-webkit-scrollbar {
  width: 10px;
}
.custom-scroll::-webkit-scrollbar-track {
  background: var(--vscode-background);
}
.custom-scroll::-webkit-scrollbar-thumb {
  background: #ccc;
  border-radius: var(--vscode-radius-sm, 4px);
}
.custom-scroll::-webkit-scrollbar-thumb:hover {
  background: #aaa;
}
.tooltip-bubble {
  display: none;
}
@property --tw-rotate-x { syntax: "*"; inherits: false; }
@property --tw-rotate-y { syntax: "*"; inherits: false; }
@property --tw-rotate-z { syntax: "*"; inherits: false; }
@property --tw-skew-x { syntax: "*"; inherits: false; }
@property --tw-skew-y { syntax: "*"; inherits: false; }
@property --tw-border-style { syntax: "*"; inherits: false; initial-value: solid; }
@property --tw-shadow { syntax: "*"; inherits: false; initial-value: 0 0 #0000; }
@property --tw-shadow-color { syntax: "*"; inherits: false; }
@property --tw-shadow-alpha { syntax: "<percentage>"; inherits: false; initial-value: 100%; }
@property --tw-inset-shadow { syntax: "*"; inherits: false; initial-value: 0 0 #0000; }
@property --tw-inset-shadow-color { syntax: "*"; inherits: false; }
@property --tw-inset-shadow-alpha { syntax: "<percentage>"; inherits: false; initial-value: 100%; }
@property --tw-ring-color { syntax: "*"; inherits: false; }
@property --tw-ring-shadow { syntax: "*"; inherits: false; initial-value: 0 0 #0000; }
@property --tw-inset-ring-color { syntax: "*"; inherits: false; }
@property --tw-inset-ring-shadow { syntax: "*"; inherits: false; initial-value: 0 0 #0000; }
@property --tw-ring-inset { syntax: "*"; inherits: false; }
@property --tw-ring-offset-width { syntax: "<length>"; inherits: false; initial-value: 0px; }
@property --tw-ring-offset-color { syntax: "*"; inherits: false; initial-value: #fff; }
@property --tw-ring-offset-shadow { syntax: "*"; inherits: false; initial-value: 0 0 #0000; }
@property --tw-outline-style { syntax: "*"; inherits: false; initial-value: solid; }
@property --tw-blur { syntax: "*"; inherits: false; }
@property --tw-brightness { syntax: "*"; inherits: false; }
@property --tw-contrast { syntax: "*"; inherits: false; }
@property --tw-grayscale { syntax: "*"; inherits: false; }
@property --tw-hue-rotate { syntax: "*"; inherits: false; }
@property --tw-invert { syntax: "*"; inherits: false; }
@property --tw-opacity { syntax: "*"; inherits: false; }
@property --tw-saturate { syntax: "*"; inherits: false; }
@property --tw-sepia { syntax: "*"; inherits: false; }
@property --tw-drop-shadow { syntax: "*"; inherits: false; }
@property --tw-drop-shadow-color { syntax: "*"; inherits: false; }
@property --tw-drop-shadow-alpha { syntax: "<percentage>"; inherits: false; initial-value: 100%; }
@property --tw-drop-shadow-size { syntax: "*"; inherits: false; }
@layer properties {
  @supports ((-webkit-hyphens: none) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color:rgb(from red r g b)))) {
    *,
    ::before,
    ::after,
    ::backdrop {
      --tw-rotate-x: initial;
      --tw-rotate-y: initial;
      --tw-rotate-z: initial;
      --tw-skew-x: initial;
      --tw-skew-y: initial;
      --tw-border-style: solid;
      --tw-shadow: 0 0 #0000;
      --tw-shadow-color: initial;
      --tw-shadow-alpha: 100%;
      --tw-inset-shadow: 0 0 #0000;
      --tw-inset-shadow-color: initial;
      --tw-inset-shadow-alpha: 100%;
      --tw-ring-color: initial;
      --tw-ring-shadow: 0 0 #0000;
      --tw-inset-ring-color: initial;
      --tw-inset-ring-shadow: 0 0 #0000;
      --tw-ring-inset: initial;
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-offset-shadow: 0 0 #0000;
      --tw-outline-style: solid;
      --tw-blur: initial;
      --tw-brightness: initial;
      --tw-contrast: initial;
      --tw-grayscale: initial;
      --tw-hue-rotate: initial;
      --tw-invert: initial;
      --tw-opacity: initial;
      --tw-saturate: initial;
      --tw-sepia: initial;
      --tw-drop-shadow: initial;
      --tw-drop-shadow-color: initial;
      --tw-drop-shadow-alpha: 100%;
      --tw-drop-shadow-size: initial;
    }
  }
}

/* angular:styles/global:styles */
/*# sourceMappingURL=styles.css.map */
`;
